#!/usr/bin/env bash
# Script displaying file's `/etc/passwd` content.
#  Only displays the username, user id, and user home directory path.

file="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$file"
