#!/usr/bin/env bash
# Script parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#  code of each log, in sorted order.

file="apache-access.log"
awk -F' ' '{ print $1, $9}' $file | sort | uniq -c|sort -nr
