#!/usr/bin/env bash
# Script looping through 1 to 10 using while

m=1

while [ $m -le 10 ]
do
    if [ $m -eq 4 ]
    then
        echo "bad luck"
    elif [ $m -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((m++))
done
