#!/usr/bin/env bash
# Script displaying time for 12 hrs and 59 minutes.
# Hours from 0 to 12
# Minutes from 1 to 59

hr=0

while [ $hr -le 12 ]
do
  echo "Hour: $hr"
  min=1
  while [ $min -le 59 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( hr++ ))
done
